#!/bin/bash
PATH_GUETZLI=`which guetzli`
PATH_GIT=`which git`
folder=`pwd`

if [[ $UID != 0 ]]; then
	echo "Please this script with sudo"
	echo "sudo $0 $*"
	exit 1
elif [ -z "$PATH_GUETZLI" ]; then
	wget https://github.com/google/guetzli/archive/master.zip
	unzip -x master
	cd guetzli-master

	make
	cd bin/Release

	mv guetzli /usr/bin

	cd $folder
	rm -rf guetzli-master
	rm master.zip
else
	echo "Guetzli already exist"
fi
